package com.github.belgadevv.pj_clt_calculator.service;

import com.github.belgadevv.pj_clt_calculator.dto.UserLoginDTO;
import com.github.belgadevv.pj_clt_calculator.dto.UserRegistrationDTO;
import com.github.belgadevv.pj_clt_calculator.entity.User;
import com.github.belgadevv.pj_clt_calculator.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Optional;


@Service
@RequiredArgsConstructor
public class UserService {


    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;


    // register Method
    public User cadastrarUsuario(UserRegistrationDTO dto) {

        // double check mechanism
        if (!dto.getSenha().equals(dto.getConfirmacaoSenha())) {
            throw new RuntimeException("As senhas não coincidem!");
        }

        // check if informed cpf is already in use
        Optional<User> usuarioExistente = userRepository.findByCpf(dto.getCpf());
        if (usuarioExistente.isPresent()) { // .isPresent() check if its null
            throw new RuntimeException("Este CPF já está cadastrado no sistema!");
        }

        // Creates the User entity using the DTO data.
        User novoUsuario = new User();
        novoUsuario.setCpf(dto.getCpf());
        // The password is encrypted with BCrypt before being stored.
        novoUsuario.setPasswordHash(passwordEncoder.encode(dto.getSenha()));

        // The UUID is automatically generated by Spring when saving.
        return userRepository.save(novoUsuario);
    }

    // Método responsável por autenticar o usuário no sistema
    // Recebe um DTO de login com CPF e senha
    public void autenticar(UserLoginDTO dto) {

        // search user by cpf, throws an exception if it doesn't find...
        User usuario = userRepository.findByCpf(dto.getCpf()).orElseThrow(() -> new RuntimeException("Usuário não encontrado com o CPF informado!"));

        // Bycript re-encrypts the entered password and compare - if it not equal throws an exception
        if (!passwordEncoder.matches(dto.getSenha(), usuario.getPasswordHash())) {
            throw new RuntimeException("Senha incorreta!");
        }


    }
}